read me file on python-exception
